month = input("What's the name of the 12th month of the calendar year?")
month = input("What's the name of the 12th month of the calendar year?: ")
month = input("What's the name of the 12th month of the calendar year? ")
lowercase_autobot = autobot.lower()
ninjabelts.append('bronze')
ninjabelts.remove('blue')